name: Deploy Web App

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  deploy_webapp:
    environment: ${{ inputs.deploy_env }}
    runs-on: ubuntu-latest
    steps:
      - name: Select environment
        run: |
          echo "Deploying to ${{ inputs.deploy_env }}"

      - name: Azure login
        uses: ./.github/workflows/steps/azure/login
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy container to Web App
        uses: ./.github/workflows/steps/azure/deploy-webapp
        with:
          azure_webapp_name: ${{ vars.AZURE_WEBAPP_NAME }}
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
