# Build stage: checkout -> app build -> container build/tag/push.
parameters:
  app_name: ""
  image_name: ""
  image_tag: ""
  registry_url: ""
  registry_repository: ""
  build_command: ""
  container_build_command: ""
  container_tag_command: ""
  container_push_command: ""

stage: build
jobs:
  - template: ../jobs/build-job.yml
    parameters:
      app_name: "${{ parameters.app_name }}"
      image_name: "${{ parameters.image_name }}"
      image_tag: "${{ parameters.image_tag }}"
      registry_url: "${{ parameters.registry_url }}"
      registry_repository: "${{ parameters.registry_repository }}"
      build_command: "${{ parameters.build_command }}"
      container_build_command: "${{ parameters.container_build_command }}"
      container_tag_command: "${{ parameters.container_tag_command }}"
      container_push_command: "${{ parameters.container_push_command }}"
