name: Podman Tag Image

inputs:
  image_name:
    required: true
  image_tag:
    required: true

runs:
  using: composite
  steps:
    - name: Tag image for GHCR
      run: |
        podman tag \
          "${{ inputs.image_name }}:${{ inputs.image_tag }}" \
          "ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}"
      shell: bash
