name: Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      template:
        required: true
        type: string
      context:
        required: false
        type: string
        default: "."
      containerfile:
        required: false
        type: string
        default: Containerfile
      build_args:
        required: false
        type: string
        default: ""
    secrets:
      GHCR_TOKEN:
        required: true
    outputs:
      image_name:
        value: ${{ inputs.image_name }}
      image_tag:
        value: ${{ inputs.image_tag }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Build image with Podman
        uses: xdevhq/devops-templates/.github/actions/podman/build-image@main
        with:
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
          context: ${{ inputs.context }}
          containerfile: ${{ inputs.containerfile }}
          template: ${{ inputs.template }}
          build_args: >-
            ${{ inputs.build_args }}
            --build-arg GITHUB_USERNAME=${{ github.actor }}
            --build-arg GITHUB_PACKAGES_TOKEN=${{ secrets.GHCR_TOKEN }}

      - name: Tag image for GHCR
        uses: xdevhq/devops-templates/.github/actions/podman/tag-image@main
        with:
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}

      - name: Login to GHCR
        run: |
          podman login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GHCR_TOKEN }}"

      - name: Push image to GHCR
        uses: xdevhq/devops-templates/.github/actions/podman/push-image@main
        with:
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
