name: Build Container Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build image with Podman
        uses: alexhovy/devops-templates/.github/actions/podman/build-image@main
        with:
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
