name: NuGet Package

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        type: string
        default: "8.0.x"
      project_path:
        required: true
        type: string
      package_version:
        required: false
        type: string
        default: ""
      configuration:
        required: false
        type: string
        default: Release
      source_url:
        required: false
        type: string
        default: "https://api.nuget.org/v3/index.json"
      source_username:
        required: false
        type: string
        default: ""
    secrets:
      NUGET_API_KEY:
        required: true
      SOURCE_PASSWORD:
        required: false

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Restore dependencies
        uses: alexhovy/devops-templates/.github/actions/dotnet/restore@main
        with:
          project_path: ${{ inputs.project_path }}
          source_url: ${{ inputs.source_url }}
          source_username: ${{ inputs.source_username }}
          source_password: ${{ secrets.SOURCE_PASSWORD }}

      - name: Pack NuGet package
        uses: alexhovy/devops-templates/.github/actions/dotnet/pack@main
        with:
          project_path: ${{ inputs.project_path }}
          configuration: ${{ inputs.configuration }}
          version: ${{ inputs.package_version }}
          output_path: ./artifacts/nuget

      - name: Publish NuGet package
        uses: alexhovy/devops-templates/.github/actions/dotnet/push-package@main
        with:
          packages_glob: ./artifacts/nuget/*.nupkg
          source_url: ${{ inputs.source_url }}
          api_key: ${{ secrets.NUGET_API_KEY }}
