name: Push Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Tag image for GHCR
        uses: alexhovy/devops-templates/.github/workflows/steps/podman/tag-image@main
        with:
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}

      - name: Login to GHCR
        run: |
          podman login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Push image to GHCR
        uses: alexhovy/devops-templates/.github/workflows/steps/podman/push-image@main
        with:
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
