name: Release

on:
  workflow_call:
    inputs:
      deploy_env:
        description: "GitHub Environment name (e.g., dev, test, prod)"
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
  workflow_dispatch: {}

jobs:
  build:
    # Stage: build
    uses: ./.github/workflows/build-stage.yml
    with:
      app_name: ${{ github.event.repository.name }}
      image_name: ${{ github.event.repository.name }}
      image_tag: ${{ github.sha }}

  deploy:
    # Stage: deploy
    needs: build
    uses: ./.github/workflows/deploy-stage.yml
    with:
      deploy_env: ${{ inputs.deploy_env }}
      image_name: ${{ github.event.repository.name }}
      image_tag: ${{ github.sha }}
