name: Release

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
  workflow_dispatch: {}

jobs:
  build:
    # Stage: build
    uses: ./stages/build-stage.yml
    with:
      app_name: ${{ github.event.repository.name }}
      image_name: ${{ github.event.repository.name }}
      image_tag: ${{ github.sha }}

  deploy:
    # Stage: deploy
    needs: build
    uses: ./stages/deploy-stage.yml
    with:
      deploy_env: prod
      image_name: ${{ github.event.repository.name }}
      image_tag: ${{ github.sha }}
